### ISSUE TITLE
do we really need gibbs to be a subcommand?

### ISSUE THREAD

**Issue by gregcaporaso** [biota/sourcetracker2#65]
Since it's the only one, would it be more intuitive if we just called ``sourcetracker2`` rather than ``sourcetracker2 gibbs``? Or are we planning to add others? If we do keep it, for users, the command ``gibbs`` probably isn't the most useful. Maybe ``track`` (or something along those lines) would be more intuitive (i.e., you don't need to know implementation details of the methods to understand the command name)?

**Comment by wdwvt1** [comment]
I think yes because we also want to have other methods available - specifically rf, svm, ols, lda. I think we could have a second command for all of these together, and few if any parameters exposed. The idea of giving the user access to these faster running/simpler alternatives has been voiced by most people I have talked to so far.

**Comment by gregcaporaso** [comment]
Ok, makes sense.
